## `exploratory-data-analysis.ipynb`

The purpose of this Jupyter notebook is to simply explore and have a look at the dataset.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'retina'
plt.style.use('seaborn-darkgrid')

In [2]:
data1 = pd.read_csv('../data/M2PHDS_19-20_OMICS_CLIN_DATA_MAARS_all_Fri_Apr_04_14h_CEST_2014.csv', sep='\t')
data1.head()

,sample_id,clinical_group,anatomical_location,anatomical_location_label,lesional,MAARS_identifier,Institution,CUSTOM_Age,Gender,Known_Allergies_v2..Pseudo_Drug_Allergy,...,Other_concurrent_chronic_diseases_v2..Others,Other_concurrent_chronic_diseases_v2..Diabetes_.non.insulin.,Other_concurrent_chronic_diseases_v2..Thyroid_dysfunction,Other_concurrent_chronic_diseases_v2..Asthma,Other_concurrent_chronic_diseases_v2..Hypertension,Global_Assessment_Score,CUSTOM_Malignancies_._skin,CUSTOM_Malignancies_._other,CUSTOM_Fam._hist._Atopic_dermatitis,CUSTOM_Family_History_of_Psoriasis
0,MAARS_3_018_02,AD,posterior_thigh,PT,NON_LES,MAARS_3_018,UH,25,Male,False,...,False,False,False,False,False,moderate,False,False,False,NaN
1,MAARS_3_018_01,AD,posterior_thigh,PT,LES,MAARS_3_018,UH,25,Male,False,...,False,False,False,False,False,moderate,False,False,False,NaN
2,MAARS_3_018_03,AD,posterior_thigh,PT,LES,MAARS_3_018,UH,25,Male,False,...,False,False,False,False,False,moderate,False,False,False,NaN
3,MAARS_3_018_04,AD,posterior_thigh,PT,NON_LES,MAARS_3_018,UH,25,Male,False,...,False,False,False,False,False,moderate,False,False,False,NaN
4,MAARS_3_082_02,AD,posterior_thigh,PT,NON_LES,MAARS_3_082,UH,62,Male,False,...,False,False,False,False,False,moderate,False,False,True,NaN

In [3]:
data2 = pd.read_csv('../data/M2PHDS_19-20_OMICS_CLIN_DATA_MAARS_AD_full_20190131_12-34-49.csv', sep='\t')
data2.head()

,patient#Identification#MAARS identifier (MAARS_identifier),patient#Identification#Date of first visit (Date_of_first_visit),patient#Identification#Institution (Institution),patient#Identification#Physician (Physician),patient#Inclusion/Exclusion criteria#Inclusion criteria#Written informed consent (Written_informed_consent),patient#Inclusion/Exclusion criteria#Inclusion criteria#18 years old or more (18_years_old_or_more),"patient#Inclusion/Exclusion criteria#Inclusion criteria#Patients with Atopic Dermatitis, diagnosed using Hanifin-Rajka Criteria (Patients_with_Atopic_Dermatitis,_diagnosed_using_Hanifin-Rajka_Criteria)",patient#Inclusion/Exclusion criteria#Exclusion criteria#Subject unable to give written informed consent (Subject_unable_to_give_written_informed_consent),patient#Inclusion/Exclusion criteria#Exclusion criteria#Subject has no allergen-specific IgE and no allergen-specific immediate type reactions (Subject_has_no_allergen-specific_IgE_and_no_allergen-specific_immediate_type_reactions),patient#Inclusion/Exclusion criteria#Exclusion criteria#Subjects who have received treatment at the biopsy site at least 2 weeks prior to screening (Subjects_who_have_received_treatment_at_the_biopsy_site_at_least_2_weeks_prior_to_screening),...,blood for genomic DNA#blood for genomic DNA#Excluded (Excluded),blood for genomic DNA#blood for genomic DNA#Exclusion comments (Exclusion_comments),blood for PBMC#blood for PBMC#MAARS Sample identifier (MAARS_Sample_identifier),blood for PBMC#blood for PBMC#Sampling date (Sampling_date),blood for PBMC#blood for PBMC#Excluded (Excluded),blood for PBMC#blood for PBMC#Exclusion comments (Exclusion_comments),plasma#plasma#MAARS Sample identifier (MAARS_Sample_identifier),plasma#plasma#Sampling date (Sampling_date),plasma#plasma#Excluded (Excluded),plasma#plasma#Exclusion comments (Exclusion_comments)
0,MAARS_1_003,06/12/12,HHU,Homey,Yes,Yes,Yes,No,No,No,...,NaN,NaN,MAARS_1_003_08,06/12/12,NaN,NaN,MAARS_1_003_09,06/12/12,NaN,NaN
1,MAARS_1_008,15/02/12,HHU,Baran,Yes,Yes,Yes,No,No,No,...,NaN,NaN,MAARS_1_008_08,NaN,NaN,NaN,MAARS_1_008_09,NaN,NaN,NaN
2,MAARS_1_016,14/03/12,HHU,Baran,Yes,Yes,Yes,No,No,No,...,NaN,NaN,MAARS_1_016_08,09/12/11,NaN,NaN,MAARS_1_016_09,09/12/11,NaN,NaN
3,MAARS_1_017,14/03/12,HHU,Baran,Yes,Yes,Yes,No,No,No,...,NaN,NaN,MAARS_1_017_08,14/03/12,NaN,NaN,MAARS_1_017_09,14/03/12,NaN,NaN
4,MAARS_1_044,09/05/12,HHU,Jahn,Yes,Yes,Yes,No,No,No,...,NaN,NaN,MAARS_1_044_08,09/05/12,NaN,NaN,MAARS_1_044_09,09/05/12,NaN,NaN

In [4]:
norm_data = pd.read_csv('../data/M2PHDS_19-20_OMICS_TRANSC_MAARS_normTranscriptome_618samples_16042014.txt', sep='\t')
norm_data.head()

,MAARS_3_033_03,MAARS_3_032_03,MAARS_3_032_04,MAARS_2_012_03,MAARS_3_007_03,MAARS_3_007_04,MAARS_2_012_04,MAARS_2_004_03,MAARS_2_004_04,MAARS_2_007_04,...,MAARS_1_128_03,MAARS_2_083_03,MAARS_1_010_04,MAARS_1_036_04,MAARS_3_099_04,MAARS_1_076_03,MAARS_1_065_03,MAARS_2_044_03,MAARS_2_056_03,MAARS_1_098_04
ENSG00000000003_at,7.967,7.634,7.893,7.106,6.807,7.375,8.027,7.948,7.606,8.432,...,8.813,7.868,8.643,8.549,8.358,8.157,7.828,7.866,7.705,7.837
ENSG00000000005_at,5.075,4.886,5.312,4.187,3.958,3.983,6.050,3.980,4.163,6.236,...,4.981,4.004,4.451,4.586,6.048,5.950,5.962,5.474,4.281,4.097
ENSG00000000419_at,9.043,9.411,9.624,9.430,9.809,9.696,9.809,9.859,9.582,9.477,...,9.726,9.764,9.668,9.274,9.669,9.471,9.382,9.816,9.781,10.130
ENSG00000000457_at,7.154,7.111,7.161,7.247,6.846,7.076,7.254,6.941,7.127,6.722,...,7.214,7.032,7.088,7.218,7.187,7.007,7.116,7.023,6.718,7.182
ENSG00000000460_at,5.992,5.819,5.931,5.881,5.975,5.288,5.236,5.928,5.781,5.601,...,5.497,5.511,5.524,5.773,5.419,5.756,5.967,5.363,5.513,6.068

#### All samples in gene dataset are available in `M2PHDS_19-20_OMICS_CLIN_DATA_MAARS_all_Fri_Apr_04_14h_CEST_2014.csv`

In [5]:
len(set(data1['sample_id'].values.astype(str)).intersection(set(np.array(list(norm_data)).astype(str))))

618

In [6]:
sum([s in data1['sample_id'].values.astype(str) for s in np.array(list(norm_data)).astype(str)])

618

In [7]:
print(data1.shape)
print(data2.shape)
print(norm_data.shape)

(1317, 34)
(94, 297)
(32633, 618)

#### No Duplicates

In [8]:
len(data1['sample_id'].values) == len(np.unique(data1['sample_id'].values))

True

#### All gene names being with `_at`

In [9]:
all(s == '_at' for s in [s[-3:] for s in norm_data.index.values])

True

In [10]:
class Patient:
    def __init__(self, identifier, clinical_group, sample_dict):
        '''
        Can add more attributes here
        '''
        assert identifier[:6] == 'MAARS_'
        assert isinstance(sample_dict, dict)
        assert len(set(sample_dict.values()).intersection({'LES', 'NON_LES'})) > 0
        assert clinical_group in ['AD', 'PSO', 'CTRL']
        
        self.identifier     = identifier
        self.clinical_group = clinical_group
        self.sample_dict    = sample_dict
        self.summary_transcriptomes = {sample: sample_dict[sample] for sample in set(list(norm_data)).intersection(set(sample_dict.keys()))}
        
    def __str__(self):
        part1 = 'Patient_id:\t\t\t{}\nClinical Group:\t\t\t{}\nNumber of samples:\t\t{}\n'.format(self.identifier, self.clinical_group, len(self.sample_dict))
        part2 = 'Transcriptome summary:\n' + ''.join(['\t{}: {}\n'.format(_id, self.sample_dict[_id]) for _id in self.summary_transcriptomes])
        
        return part1 + part2

In [11]:
# ad = 0
# not_ad = 0

list_patients = []

for patient_id in np.unique(data1['MAARS_identifier'].values):
    patient_data = data1[data1['MAARS_identifier'] == patient_id][['MAARS_identifier', 'clinical_group', 'sample_id', 'lesional']]
    assert len(set(patient_data['clinical_group'])) == 1
    
    sample_dict = {_id: _les for (_id, _les) in list(zip(patient_data['sample_id'], patient_data['lesional']))}
    
    list_patients.append(Patient(patient_data['MAARS_identifier'].values[0],
                         patient_data['clinical_group'].values[0],
                         sample_dict))
#     if set(patient_data['clinical_group']) == {'AD'}:
#         ad += 1
#     else:
#         not_ad += 1

In [24]:
len(set(data1['MAARS_identifier'].values).difference(set(data2['patient#Identification#MAARS identifier (MAARS_identifier)'].values)))

246

In [18]:
len(data2['patient#Identification#MAARS identifier (MAARS_identifier)'].values)

94

In [19]:
len(data1)

1317

In [21]:
print_limit = 10

for i, patient in enumerate(list_patients):
    if i > print_limit:
        break
    print(patient)

Patient_id:			MAARS_1_002
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_002_04: NON_LES
	MAARS_1_002_03: LES

Patient_id:			MAARS_1_003
Clinical Group:			AD
Number of samples:		4
Transcriptome summary:
	MAARS_1_003_03: LES
	MAARS_1_003_04: NON_LES

Patient_id:			MAARS_1_004
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_004_04: NON_LES
	MAARS_1_004_03: LES

Patient_id:			MAARS_1_005
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_005_03: LES
	MAARS_1_005_04: NON_LES

Patient_id:			MAARS_1_006
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_006_03: LES
	MAARS_1_006_04: NON_LES

Patient_id:			MAARS_1_007
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_007_04: NON_LES
	MAARS_1_007_03: LES

Patient_id:			MAARS_1_008
Clinical Group:			AD
Number of samples:		4
Transcriptome summary:
	MAARS_1_008_04: NON_LES
	MAARS_1_008_03: LES

Patient_id:			MAARS_1_009
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_009_04: NON_LES
	MAARS_1_009_03: LES

Patient_id:			MAARS_1_010
Clinical Group:			PSO
Number of samples:		4
Transcriptome summary:
	MAARS_1_010_04: NON_LES
	MAARS_1_010_03: LES

Patient_id:			MAARS_1_011
Clinical Group:			CTRL
Number of samples:		4
Transcriptome summary:
	MAARS_1_011_04: NON_LES

Patient_id:			MAARS_1_012
Clinical Group:			CTRL
Number of samples:		2
Transcriptome summary:
	MAARS_1_012_03: NON_LES